name: PR CI

on:
  pull_request:
    branches:
      - main

jobs:
  test-and-build:
    name: Test and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run Tests
        run: go test -v ./...

      - name: Test Build
        run: go build -v ./cmd/crawl-url
